import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      "supabase/.branches",
      "supabase/.temp",
      // Regenerated by the vite plugin on every config load — see .prettierignore.
      "**/list-tools.ts",
      "**/invoke-tool/**",
      "**/oauth-protected-resource.ts",
      "src/routes/mcp.ts",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
          patterns: [
            {
              // NEUVTO_CODING_STANDARDS.md §1 — modules are imported by their root,
              // never by reaching into their internals.
              group: ["**/modules/*/handlers/*", "**/modules/*/contracts/*"],
              message: "Import a module by its root (e.g. @/modules/leave), not its internals.",
            },
            {
              // NEUVTO_CODING_STANDARDS.md §9 — the portability contract. Lovable's
              // proprietary APIs stay reachable from one directory only.
              group: ["**/integrations/lovable", "**/integrations/lovable/*"],
              message:
                "Lovable APIs are quarantined. Go through the wrapper in src/platform/auth/ — see NEUVTO_CODING_STANDARDS.md §9.",
            },
            {
              // D66 — the Worker holds no secrets, and that is a property worth
              // keeping rather than a coincidence. client.server.ts is generated by
              // Lovable and exports an RLS-bypassing service-role client that
              // nothing imports; SUPABASE_SERVICE_ROLE_KEY is deliberately absent
              // from Cloudflare as a result.
              //
              // The trap this rule exists for: importing it throws at runtime with
              // "Missing Supabase environment variable(s): SUPABASE_SERVICE_ROLE_KEY.
              // Connect Supabase in Lovable Cloud." That message asks the reader to
              // put a key that reads and writes EVERY tenant's data onto an edge
              // worker — advice that is wrong for this repository and arrives at the
              // exact moment somebody is debugging under pressure. This rule fires
              // first, at the import, with the argument instead.
              // Every form the import can take. A sibling relative import
              // ("./client.server") from inside src/integrations/supabase/ was NOT
              // caught by the path-qualified patterns alone — found by writing a
              // probe in that directory and watching it pass. That directory is
              // precisely where Lovable generates code, so the hole was the one
              // that mattered.
              group: [
                "**/integrations/supabase/client.server",
                "**/supabase/client.server",
                "**/client.server",
                "./client.server",
                "../client.server",
              ],
              message:
                "client.server.ts bypasses RLS and needs SUPABASE_SERVICE_ROLE_KEY, which the Worker deliberately does not have (D66). Privileged work goes through a SECURITY DEFINER RPC that checks is_platform_admin() — that is how /neuvto-hq already does it, with no service key. If you genuinely need the key, see ENVIRONMENTS.md 'The service role key' before adding this import.",
            },
          ],
        },
      ],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      // Standards §3 — unused code accumulates invisibly when this is off.
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      // Standards §3 — `any` defeats the type system it is embedded in.
      "@typescript-eslint/no-explicit-any": "error",
    },
  },

  // The quarantine itself, and generated files, are exempt from their own rules.
  {
    files: ["src/integrations/lovable/**", "src/integrations/supabase/types.ts"],
    rules: { "no-restricted-imports": "off", "@typescript-eslint/no-explicit-any": "off" },
  },

  eslintPluginPrettier,
);
