/**
 * The picture every share of this company shows.
 *
 * `og:image` and `twitter:image` pointed at a LOVABLE BUILD PREVIEW until 8 Aug
 * 2026 — a `pub-….r2.dev` bucket with `id-preview` and `lovable.app` in the
 * filename. Live and serving, so it looked fine: every share on LinkedIn or
 * WhatsApp fetched Neuvto's picture from a bucket Neuvto does not own, and it
 * would have gone blank without warning the day that bucket was pruned.
 *
 * Two properties of this value are unobservable from inside the product. Nothing
 * in the app renders it; the only feedback is somebody pasting a link into a
 * chat, and by then it has already been seen wrong.
 *
 *   ABSOLUTE.  Open Graph consumers do not resolve relative URLs. "/social-card.png"
 *              is not a smaller bug than a wrong host — it is silently NO IMAGE,
 *              and the page still previews perfectly in a browser.
 *   OURS.      Not a preview bucket belonging to a tool we no longer deploy with.
 *
 * ── no DOM, deliberately
 *
 * `head()` is a plain function returning plain data, so this runs in the default
 * `node` environment: rendering a router to read a string back out of a <meta>
 * would prove the same thing at fifty times the cost and add a mocked router to
 * the list of things that could make it pass. Only the router's module-load
 * calls are stubbed.
 *
 * What this does NOT prove is that https://neuvto.com/social-card.png exists and
 * is 1200×630. Nothing in a test suite that may not touch the network can; the
 * file is generated by scripts/generate-social-card.py and lives in public/.
 */

import { describe, expect, it, vi } from "vitest";

vi.mock("@tanstack/react-router", () => ({
  createRootRouteWithContext: () => (opts: unknown) => opts,
  Outlet: () => null,
  Link: () => null,
  useRouter: () => ({}),
  HeadContent: () => null,
  Scripts: () => null,
}));

import { Route } from "./__root";

type Meta = { name?: string; property?: string; content?: string; title?: string };

const meta: Meta[] = (Route as unknown as { head: () => { meta: Meta[] } }).head().meta;

/** Every meta entry that carries a URL for a share card. */
const imageMetas = meta.filter((m) => m.property === "og:image" || m.name === "twitter:image");

function describeMeta(m: Meta): string {
  return `${m.property ?? m.name ?? "?"} = ${m.content ?? "(no content)"}`;
}

describe("root head — the social card", () => {
  it("gives both scrapers an absolute URL on our own origin", () => {
    // Both, not either. They are read by different products — Open Graph by
    // LinkedIn, WhatsApp and Slack; `twitter:image` by X — so one correct value
    // and one relative path is a blank card on half the places a link is shared.
    expect(imageMetas.map((m) => (m.property ? m.property : m.name))).toEqual([
      "og:image",
      "twitter:image",
    ]);

    // Listed rather than counted so a regression prints the value it found. A
    // leading-slash path fails here and nowhere else in the suite.
    const notAbsolute = imageMetas
      .filter((m) => !/^https:\/\//.test(m.content ?? ""))
      .map(describeMeta);
    expect(notAbsolute).toEqual([]);

    const elsewhere = imageMetas
      .filter((m) => new URL(m.content!).origin !== "https://neuvto.com")
      .map(describeMeta);
    expect(elsewhere).toEqual([]);
  });

  it("has nothing anywhere in the head still pointing at the old build previews", () => {
    // Scoped to the whole meta list rather than to the two image tags. The
    // preview URL is the kind of value that gets copied sideways into a
    // canonical, an alternate or a second card tag by whoever adds the next one.
    const strays = meta
      .filter((m) => /lovable\.app|r2\.dev|id-preview/i.test(m.content ?? ""))
      .map(describeMeta);
    expect(strays).toEqual([]);

    // A filter over an empty list passes forever. If `head()` stops returning
    // meta — or the router mock starts swallowing it — this says so first.
    expect(meta.length).toBeGreaterThanOrEqual(15);
  });
});
